### ISSUE TITLE
0.2.0 meta-issue

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epinowcast#191]
- [ ] Complete all linked issues in #180 
- [ ] Merge #180 
- [ ] Add a summary section to the release note and thank all authors
- [ ] Post on the community site to flag to all authors and request a final tire kicking
- [ ] Write a release note for the epinowcast.org site and share on the community site for edits
- [ ] Post the release note via social media channels, our community site, networks etc.

**Comment by seabbs** [comment]
As it seems like there is more to discuss I have bumped #166 from the release timeline. However, we really should sort it out before prompting as its quite a killer problem. Flagging here so people are aware when looking at this as a prerelease/candidate release.

**Comment by seabbs** [comment]
Gearing up to make this a full release (https://community.epinowcast.org/t/0-2-0-package-pre-release/103/5). Likely early next week.
