### ISSUE TITLE
`0.2.1` Meta issue and release checklist - planned release date 2023-04-25

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epinowcast#243]
The current roadmap for `0.2.1` can be found here: https://github.com/orgs/epinowcast/projects/3

After these issues are complete the following needs to be done:

- [x] Remove the `@develop` tag for all `touchstone` custom action calls and replace with `@main`.
- [x] Write a summary of the release in the news + package version to release in a new PR.
- [x] @seabbs review this PR.
- [x] Test the examples and `README`.
- [x] Make a community post linking to the planned release and request a review.
- [x] Wait a day.
- [x] If all reviews are passing merge release
- [x] Make a GitHub release (make sure to use the automated PR release notes builder and augment with the news file)
- [x] Share the release via the appropriate channels (i.e community site, Mastodon).
- [x] Archive the `0.2.1` project.
- [x] Make a `0.5.0` project.
- [x] 🥳

**Comment by seabbs** [comment]
Done done 🥳  time
